import Foundation

public protocol AccessTokenProvider: AnyObject {
	/// Returns an OAuth access token or nil if one does not exist.
	var accessToken: String? { get }

	/// Renews the access token. This should be run when the backend returns a HTTP status indicating that the access token
	/// has become invalid for some reason. The implementation of this method must run a full OAuth flow and return the
	/// token generated by the backend.
	///
	/// - Parameters:
	///   - reason: The authorization related sub status returned on the failing request. This is optional to allow for using a
	/// default
	/// value in unknown cases, and also to handle the case where the accessToken itself is nil.
	func renewAccessToken(status: Int?) async throws
}
