{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "User v2 - beta",
    "description" : "The User API v2 provides a set of JSON:API compatible endpoints for getting the TIDAL users, and more",
    "contact" : {
      "url" : "https://github.com/orgs/tidal-music/discussions"
    },
    "version" : "1.0.0",
    "x-url-compatible-spec-id" : "user-v2",
    "x-spec-default-endpoint-url-unique-name" : "get-me-v2"
  },
  "servers" : [ {
    "url" : "https://openapi.tidal.com/v2",
    "description" : "Production"
  } ],
  "tags" : [ {
    "name" : "UserCollections"
  }, {
    "name" : "UserEntitlements"
  }, {
    "name" : "UserPublicProfilePicks"
  }, {
    "name" : "UserPublicProfiles"
  }, {
    "name" : "UserRecommendations"
  }, {
    "name" : "Users"
  } ],
  "paths" : {
    "/userCollections/{id}" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Get single userCollection",
        "description" : "Retrieves userCollection details by an unique id.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-single-userCollection",
          "json-api-available-relationships" : [ "albums", "artists", "playlists" ]
        }
      }
    },
    "/userCollections" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Get all userCollections",
        "description" : "Retrieves all userCollection details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-usercollections",
          "json-api-available-relationships" : [ "albums", "artists", "playlists" ],
          "json-api-available-filters" : [ {
            "name" : "id"
          } ]
        }
      }
    },
    "/userCollections/me" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Get current user's userCollection data",
        "description" : "Retrieves current user's userCollection details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-my-userCollection-data",
          "json-api-available-relationships" : [ "albums", "artists", "playlists" ]
        }
      }
    },
    "/userCollections/{id}/relationships/albums" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: albums",
        "description" : "Retrieves albums relationship details of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userCollection-albums-relationship",
          "json-api-available-relationships" : [ "albums" ]
        }
      },
      "post" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: albums (add)",
        "description" : "Adds items to albums relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: albums (remove)",
        "description" : "Removes items from albums relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      }
    },
    "/userCollections/{id}/relationships/artists" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: artists",
        "description" : "Retrieves artists relationship details of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userCollection-artists-relationship",
          "json-api-available-relationships" : [ "artists" ]
        }
      },
      "post" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: artists (add)",
        "description" : "Adds items to artists relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: artists (remove)",
        "description" : "Removes items from artists relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      }
    },
    "/userCollections/{id}/relationships/playlists" : {
      "get" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: playlists",
        "description" : "Retrieves playlists relationship details of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userCollection-playlists-relationship",
          "json-api-available-relationships" : [ "playlists" ]
        }
      },
      "post" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: playlists (add)",
        "description" : "Adds items to playlists relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "UserCollections" ],
        "summary" : "Relationship: playlists (remove)",
        "description" : "Removes items from playlists relationship of the related userCollection resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "collection.write" ]
        } ]
      }
    },
    "/userEntitlements/{id}" : {
      "get" : {
        "tags" : [ "UserEntitlements" ],
        "summary" : "Get single userEntitlement",
        "description" : "Retrieves userEntitlement details by an unique id.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "entitlements.read" ]
        } ]
      }
    },
    "/userEntitlements" : {
      "get" : {
        "tags" : [ "UserEntitlements" ],
        "summary" : "Get all userEntitlements",
        "description" : "Retrieves all userEntitlement details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "entitlements.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-userentitlements",
          "json-api-available-filters" : [ {
            "name" : "id"
          } ]
        }
      }
    },
    "/userEntitlements/me" : {
      "get" : {
        "tags" : [ "UserEntitlements" ],
        "summary" : "Get current user's userEntitlement data",
        "description" : "Retrieves current user's userEntitlement details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "entitlements.read" ]
        } ]
      }
    },
    "/userPublicProfilePicks" : {
      "get" : {
        "tags" : [ "UserPublicProfilePicks" ],
        "summary" : "Get all userPublicProfilePicks",
        "description" : "Retrieves all userPublicProfilePick details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-userpublicprofilepicks",
          "json-api-available-relationships" : [ "item", "userPublicProfile" ],
          "json-api-available-filters" : [ {
            "name" : "userPublicProfile.id"
          }, {
            "name" : "id"
          } ]
        }
      }
    },
    "/userPublicProfilePicks/me" : {
      "get" : {
        "tags" : [ "UserPublicProfilePicks" ],
        "summary" : "Get current user's userPublicProfilePick data",
        "description" : "Retrieves current user's userPublicProfilePick details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-my-userPublicProfilePick-data",
          "json-api-available-relationships" : [ "item", "userPublicProfile" ]
        }
      }
    },
    "/userPublicProfilePicks/{id}/relationships/item" : {
      "get" : {
        "tags" : [ "UserPublicProfilePicks" ],
        "summary" : "Relationship: item(read)",
        "description" : "Retrieves item relationship details of the related userPublicProfilePick resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfilePick-item-relationship",
          "json-api-available-relationships" : [ "item" ]
        }
      },
      "patch" : {
        "tags" : [ "UserPublicProfilePicks" ],
        "summary" : "Relationship: item (create/update/delete)",
        "description" : "Manages item relationship details of the related userPublicProfilePick resource. Use this operation if you need to create, update or delete relationship's linkage.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.write" ]
        } ]
      }
    },
    "/userPublicProfilePicks/{id}/relationships/userPublicProfile" : {
      "get" : {
        "tags" : [ "UserPublicProfilePicks" ],
        "summary" : "Relationship: userPublicProfile(read)",
        "description" : "Retrieves userPublicProfile relationship details of the related userPublicProfilePick resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfilePick-userpublicprofile-relationship",
          "json-api-available-relationships" : [ "userPublicProfile" ]
        }
      }
    },
    "/userPublicProfiles/{id}" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Get single userPublicProfile",
        "description" : "Retrieves userPublicProfile details by an unique id.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-single-userPublicProfile",
          "json-api-available-relationships" : [ "followers", "following", "publicPicks", "publicPlaylists" ]
        }
      },
      "patch" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Update single userPublicProfile",
        "description" : "Updates the existing instance of userPublicProfile's resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.write" ]
        } ]
      }
    },
    "/userPublicProfiles" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Get all userPublicProfiles",
        "description" : "Retrieves all userPublicProfile details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-userpublicprofiles",
          "json-api-available-relationships" : [ "followers", "following", "publicPicks", "publicPlaylists" ],
          "json-api-available-filters" : [ {
            "name" : "id"
          } ]
        }
      }
    },
    "/userPublicProfiles/me" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Get current user's userPublicProfile data",
        "description" : "Retrieves current user's userPublicProfile details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-my-userPublicProfile-data",
          "json-api-available-relationships" : [ "followers", "following", "publicPicks", "publicPlaylists" ]
        }
      }
    },
    "/userPublicProfiles/{id}/relationships/followers" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Relationship: followers",
        "description" : "Retrieves followers relationship details of the related userPublicProfile resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfile-followers-relationship",
          "json-api-available-relationships" : [ "followers" ]
        }
      }
    },
    "/userPublicProfiles/{id}/relationships/following" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Relationship: following",
        "description" : "Retrieves following relationship details of the related userPublicProfile resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfile-following-relationship",
          "json-api-available-relationships" : [ "following" ]
        }
      }
    },
    "/userPublicProfiles/{id}/relationships/publicPicks" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Relationship: publicPicks",
        "description" : "Retrieves publicPicks relationship details of the related userPublicProfile resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfile-publicpicks-relationship",
          "json-api-available-relationships" : [ "publicPicks" ]
        }
      }
    },
    "/userPublicProfiles/{id}/relationships/publicPlaylists" : {
      "get" : {
        "tags" : [ "UserPublicProfiles" ],
        "summary" : "Relationship: publicPlaylists",
        "description" : "Retrieves publicPlaylists relationship details of the related userPublicProfile resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "public-profile.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userPublicProfile-publicplaylists-relationship",
          "json-api-available-relationships" : [ "publicPlaylists" ]
        }
      }
    },
    "/userRecommendations/{id}" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Get single userRecommendation",
        "description" : "Retrieves userRecommendation details by an unique id.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-single-userRecommendation",
          "json-api-available-relationships" : [ "discoveryMixes", "myMixes", "newArrivalMixes" ]
        }
      }
    },
    "/userRecommendations" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Get all userRecommendations",
        "description" : "Retrieves all userRecommendation details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-userrecommendations",
          "json-api-available-relationships" : [ "discoveryMixes", "myMixes", "newArrivalMixes" ],
          "json-api-available-filters" : [ {
            "name" : "id"
          } ]
        }
      }
    },
    "/userRecommendations/me" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Get current user's userRecommendation data",
        "description" : "Retrieves current user's userRecommendation details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-my-userRecommendation-data",
          "json-api-available-relationships" : [ "discoveryMixes", "myMixes", "newArrivalMixes" ]
        }
      }
    },
    "/userRecommendations/{id}/relationships/discoveryMixes" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Relationship: discoveryMixes",
        "description" : "Retrieves discoveryMixes relationship details of the related userRecommendation resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userRecommendation-discoverymixes-relationship",
          "json-api-available-relationships" : [ "discoveryMixes" ]
        }
      }
    },
    "/userRecommendations/{id}/relationships/myMixes" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Relationship: myMixes",
        "description" : "Retrieves myMixes relationship details of the related userRecommendation resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userRecommendation-mymixes-relationship",
          "json-api-available-relationships" : [ "myMixes" ]
        }
      }
    },
    "/userRecommendations/{id}/relationships/newArrivalMixes" : {
      "get" : {
        "tags" : [ "UserRecommendations" ],
        "summary" : "Relationship: newArrivalMixes",
        "description" : "Retrieves newArrivalMixes relationship details of the related userRecommendation resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "recommendations.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-userRecommendation-newarrivalmixes-relationship",
          "json-api-available-relationships" : [ "newArrivalMixes" ]
        }
      }
    },
    "/users/{id}" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get single user",
        "description" : "Retrieves user details by an unique id.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-single-user",
          "json-api-available-relationships" : [ "entitlements", "publicProfile", "recommendations" ]
        }
      }
    },
    "/users" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get all users",
        "description" : "Retrieves all user details by available filters or without (if applicable).",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-all-users",
          "json-api-available-relationships" : [ "entitlements", "publicProfile", "recommendations" ],
          "json-api-available-filters" : [ {
            "name" : "id"
          } ]
        }
      }
    },
    "/users/me" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Get current user's user data",
        "description" : "Retrieves current user's user details.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-my-user-data",
          "json-api-available-relationships" : [ "entitlements", "publicProfile", "recommendations" ]
        }
      }
    },
    "/users/{id}/relationships/entitlements" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Relationship: entitlements(read)",
        "description" : "Retrieves entitlements relationship details of the related user resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-user-entitlements-relationship",
          "json-api-available-relationships" : [ "entitlements" ]
        }
      }
    },
    "/users/{id}/relationships/publicProfile" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Relationship: publicProfile(read)",
        "description" : "Retrieves publicProfile relationship details of the related user resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-user-publicprofile-relationship",
          "json-api-available-relationships" : [ "publicProfile" ]
        }
      }
    },
    "/users/{id}/relationships/recommendations" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Relationship: recommendations(read)",
        "description" : "Retrieves recommendations relationship details of the related user resource.",
        "security" : [ {
          "Authorization_Code_PKCE" : [ "user.read" ]
        } ],
        "x-endpoint-properties" : {
          "url-compatible-unique-name" : "get-user-recommendations-relationship",
          "json-api-available-relationships" : [ "recommendations" ]
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "Authorization_Code_PKCE" : {
        "type" : "oauth2",
        "description" : "Use this grant flow to access users personalized TIDAL data.",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://login.tidal.com/",
            "tokenUrl" : "https://auth.tidal.com/v1/",
            "scopes" : {
              "user.read" : "Read access to a user's account information, such as country and email address.",
              "entitlements.read" : "Read access to a user's entitlements",
              "playlists.read" : "Read access to a user's playlists",
              "recommendations.read" : "Read access to a user's recommendations",
              "public-profile.read" : "Read access to a user's public profile",
              "public-profile.write" : "Write access to a user's public profile"
            }
          }
        },
        "x-scopes-required-access-tier" : {
          "user.read" : "THIRD_PARTY",
          "entitlements.read" : "THIRD_PARTY",
          "playlists.read" : "THIRD_PARTY",
          "recommendations.read" : "THIRD_PARTY",
          "public-profile.read" : "INTERNAL",
          "public-profile.write" : "INTERNAL"
        }
      },
      "Client_Credentials" : {
        "type" : "oauth2",
        "description" : "Use this grant flow to access non-personalized TIDAL data.",
        "flows" : {
          "clientCredentials" : {
            "tokenUrl" : "https://auth.tidal.com/v1/",
            "scopes" : { }
          }
        }
      }
    }
  }
}