name: Run Lint Checks

on:
  workflow_call:

  pull_request:
    branches:
      - '**'

  merge_group:
    types: [checks_requested]

jobs:
  run-swiftlint:
    name: Run SwiftLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2

    - name: Get changed directories
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.swift
    - name: Run swiftlint on changed files
      run: |
        files="${{ steps.changed-files.outputs.all_changed_files }}"
        echo "Changed files: $files"
        if [[ -z $files ]]; then
          echo "No swift files were changed. Linter won't run"
        else
          ./bin/swiftlint/run-swiftlint.sh $files
        fi
